### ISSUE TITLE
Move devour to its own GitHub Org

### ISSUE THREAD

**Issue by thegrandpoobah** [devour-js/devour-client#248]
Hello, I am the current administrator of the TWG GitHub repository.  Wondering who is the current maintainer of the devour project so that I can talk to them about moving this repository to its own GitHub org.

We would like to clean up our org a bit this year and want to make sure things end up on the right places.

Please let me know and we can make sure that whatever we plan in terms of cleanup, we account for your project.

Thanks,

**Comment by auvipy** [comment]
@auvipy is one current active maintainer

**Comment by thegrandpoobah** [comment]
@auvipy thoughts on the above?

**Comment by auvipy** [comment]
I'm positive on that

**Comment by tijn** [comment]
I'm also an admin on this project and totally okay with moving it to its own org.

**Comment by thegrandpoobah** [comment]
@tijn @auvipy , correct me if I'm wrong, but it looks like there are only two things downstream are dependent on this.

1) npm
2) travis

I *think* NPM is automatic once you do a publish (and the old repo URL will autoforward as well)

Travis is a bit trickier, I'm not sure how the relationship is set up, so you might have to update that manually.

Does that sound about right?

I'd like to get this done by end of February, so if its more involved I'd love to know.

**Comment by tijn** [comment]
@auvipy shall we start a new GitHub-organization and move the repo there? The devour-organization already exists. How about "devour-js"?

**Comment by auvipy** [comment]
lets do it

**Comment by tijn** [comment]
> lets do it

@auvipy I'm on it!

**Comment by tijn** [comment]
@thegrandpoobah can you help us transfer the repository to https://github.com/devour-js ? GitHub forbids me to do it myself: 
![image](https://user-images.githubusercontent.com/18674/217287778-95ea3688-5973-4881-a017-1c33fa29d6c1.png)

**Comment by thegrandpoobah** [comment]
@tijn , to transfer this repo, I need to have repo creation rights on the devour-js org. once you give that I can transfer this over.

**Comment by thegrandpoobah** [comment]
It is done :) Thank you @tijn @auvipy . Please let me know if you need anything further.

**Comment by tijn** [comment]
Thanks @thegrandpoobah ! 

It's pretty funny that even this issue has moved over to the new organisation 😄

**Comment by auvipy** [comment]
> It is done :) Thank you @tijn @auvipy . Please let me know if you need anything further.

you can check and invite me on npm as well! my username is same as github
